package stubs;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.9
 * 2020-03-06T20:09:32.087+01:00
 * Generated source version: 2.7.9
 * 
 */
@WebServiceClient(name = "DeliveryServiceImplService", 
                  wsdlLocation = "file:/C:/Users/user/Desktop/SI4/S2/ISA-DevOps/projet-isa-devops-20-team-b-20/projet-isa-devops-20-team-b-20-client-warehouse/src/main/java/stubs/DeliveryWS.wsdl",
                  targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dronedelivery/delivery") 
public class DeliveryServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.polytech.unice.fr/si/4a/isa/dronedelivery/delivery", "DeliveryServiceImplService");
    public final static QName DeliveryServiceImplPort = new QName("http://www.polytech.unice.fr/si/4a/isa/dronedelivery/delivery", "DeliveryServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/user/Desktop/SI4/S2/ISA-DevOps/projet-isa-devops-20-team-b-20/projet-isa-devops-20-team-b-20-client-warehouse/src/main/java/stubs/DeliveryWS.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DeliveryServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/user/Desktop/SI4/S2/ISA-DevOps/projet-isa-devops-20-team-b-20/projet-isa-devops-20-team-b-20-client-warehouse/src/main/java/stubs/DeliveryWS.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DeliveryServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DeliveryServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DeliveryServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DeliveryServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DeliveryServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DeliveryServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns DeliveryService
     */
    @WebEndpoint(name = "DeliveryServiceImplPort")
    public DeliveryService getDeliveryServiceImplPort() {
        return super.getPort(DeliveryServiceImplPort, DeliveryService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DeliveryService
     */
    @WebEndpoint(name = "DeliveryServiceImplPort")
    public DeliveryService getDeliveryServiceImplPort(WebServiceFeature... features) {
        return super.getPort(DeliveryServiceImplPort, DeliveryService.class, features);
    }

}
