package stubs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.9
 * 2020-03-06T20:09:32.079+01:00
 * Generated source version: 2.7.9
 * 
 */
@WebService(targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dronedelivery/delivery", name = "DeliveryService")
@XmlSeeAlso({ObjectFactory.class})
public interface DeliveryService {

    @WebMethod
    @RequestWrapper(localName = "startDelivery", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dronedelivery/delivery", className = "stubs.StartDelivery")
    @ResponseWrapper(localName = "startDeliveryResponse", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/dronedelivery/delivery", className = "stubs.StartDeliveryResponse")
    public void startDelivery(
        @WebParam(name = "delivery_id", targetNamespace = "")
        java.lang.String deliveryId
    );
}
